// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7ZuBiWEEwBmGlHqtdUwOqE2b9YL4uvo',
    appId: '1:666302061804:web:341e6fad2b2f921d27d9c9',
    messagingSenderId: '666302061804',
    projectId: 'tinywings-d6951',
    authDomain: 'tinywings-d6951.firebaseapp.com',
    databaseURL: 'https://tinywings-d6951-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinywings-d6951.firebasestorage.app',
    measurementId: 'G-ZN91FPBQJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxduZlyyY1BO3bGhZzbP1wntOkC5yuxCM',
    appId: '1:666302061804:android:d3987cac55243a4327d9c9',
    messagingSenderId: '666302061804',
    projectId: 'tinywings-d6951',
    databaseURL: 'https://tinywings-d6951-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinywings-d6951.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA82MhJYFuQyfgb4uM4DZlE8Y07Q2Cyhss',
    appId: '1:666302061804:ios:744c7d15297f653527d9c9',
    messagingSenderId: '666302061804',
    projectId: 'tinywings-d6951',
    databaseURL: 'https://tinywings-d6951-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinywings-d6951.firebasestorage.app',
    iosBundleId: 'com.example.tinywings',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82MhJYFuQyfgb4uM4DZlE8Y07Q2Cyhss',
    appId: '1:666302061804:ios:744c7d15297f653527d9c9',
    messagingSenderId: '666302061804',
    projectId: 'tinywings-d6951',
    databaseURL: 'https://tinywings-d6951-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinywings-d6951.firebasestorage.app',
    iosBundleId: 'com.example.tinywings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl7ZuBiWEEwBmGlHqtdUwOqE2b9YL4uvo',
    appId: '1:666302061804:web:377568232ea24e0027d9c9',
    messagingSenderId: '666302061804',
    projectId: 'tinywings-d6951',
    authDomain: 'tinywings-d6951.firebaseapp.com',
    databaseURL: 'https://tinywings-d6951-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinywings-d6951.firebasestorage.app',
    measurementId: 'G-KJNSW8XKS6',
  );

}