import 'package:flutter_riverpod/flutter_riverpod.dart';

enum AppLanguage { english, bangla }

final languageProvider = StateProvider<AppLanguage>((ref) => AppLanguage.english);

final translationProvider = Provider((ref) {
  final lang = ref.watch(languageProvider);
  return lang == AppLanguage.english ? _en : _bn;
});

const Map<String, String> _en = {
  'home': 'Home',
  'donate': 'Donate',
  'impact': 'Impact',
  'profile': 'Profile',
  'settings': 'Settings',
  'language': 'Language',
  'make_donation': 'Make a Donation',
  'help_support': 'Help & Support',
  'organizations': 'Organizations',
  'hero_act': 'Heroic Act!',
  'thank_you': 'Thank You!',
  'view_ledger': 'View Impact Ledger',
  'logout': 'Log Out',
  'welcome_back': 'Welcome back',
  'social': 'Social',
  'board': 'Board',
  'needs': 'Needs',
  'total_impact': 'Total Impact Verified',
  'transparency_journal': 'Transparency Journal',
  'ledger_empty': 'No verified deliveries recorded yet.',
  'certificate_title': 'TINYWINGS HERO',
  'certificate_subtitle': 'CERTIFICATE OF IMPACT',
  'certificate_body': 'This is to formally recognize and celebrate',
  'certificate_footer': 'For their significant contribution to the underprivileged children of Bangladesh.',
  'faq_title': 'Frequently Asked Questions',
  'send_message': 'Send us a message',
  'category': 'Category',
  'subject': 'Subject',
  'message_label': 'Message',
  'submit_feedback': 'Submit Feedback',
  'my_messages': 'My Messages & Responses',
  'top_contributors': 'Top Contributors',
  'all_time': 'All Time',
  'by_org': 'By Organization',
  'select_org': 'Select Organization',
  'total': 'Total',
  'sponsors': 'Sponsors',
  'donors': 'Donors',
  'period': 'Period',
  'welcome_title': 'TinyWings',
  'welcome_subtitle': 'Connect, Care, and Support children in need',
  'login': 'Login',
  'register': 'Register',
  'start_impact': 'Start Your Impact Journey',
  'volunteering': 'Volunteering',
  'search_opps': 'Search opportunities...',
  'already_applied': 'Already Applied',
  'apply_now': 'Apply Now',
  'add_opportunity': 'Post Opportunity',
  'impact_sponsorships': 'Impact Sponsorships',
  'supports_over': 'Supports over',
  'children': 'children',
  'search_orgs': 'Search organizations...',
  'dhaka': 'Dhaka',
  'verified': 'Verified',
  'urgent': 'Urgent',
  'view_details': 'View Details',
  'profile_login_prompt': 'Login to see your profile',
  'about_me': 'ABOUT ME',
  'my_impact': 'MY IMPACT',
  'quick_actions': 'QUICK ACTIONS',
  'edit_profile': 'Edit Profile',
  'phone': 'Phone',
  'profession': 'Profession',
  'skills': 'Skills',
  'address': 'Address',
  'blood_group': 'Blood Group',
  'total_contribution': 'Total Contribution',
  'volunteer_apps': 'Volunteer Apps',
  'donation_history': 'Donation History',
  'my_sponsorships': 'My Sponsorships',
  'my_applications': 'My Applications',
  'full_name': 'Full Name',
  'email_address': 'Email Address',
  'bio': 'Bio',
  'professional_skills': 'Professional & Skills',
  'v_skills': 'Volunteering Skills',
  'location_safety': 'Location & Safety',
  'emergency_phone': 'Emergency Phone',
  'save_changes': 'Save Changes',
  'successful_update': 'Profile updated successfully!',
  'mark_all_read': 'Mark all read',
  'no_notifications': 'No notifications yet',
  'opp_board': 'Opportunity Board',
  'post_opp': 'Post Opportunity',
  'apply_method': 'How to apply',
  'deadline': 'Deadline',
  'eligibility': 'Eligibility',
  'contact_method': 'Contact Method',
  'jobs': 'Jobs',
  'scholarships': 'Scholarships',
  'admissions': 'Admissions',
  'internships': 'Internships',
  'training': 'Training',
  'fellowships': 'Fellowships',
  'mentorship': 'Mentorship',
  'housing': 'Housing',
  'opp_posted': 'Opportunity posted successfully!',
  'all': 'All',
  'notifications': 'Notifications',
  'manage': 'Manage',
};

const Map<String, String> _bn = {
  'home': 'হোম',
  'donate': 'দান করুন',
  'impact': 'প্রভাব',
  'profile': 'প্রোফাইল',
  'settings': 'সেটিংস',
  'language': 'ভাষা',
  'make_donation': 'একটি দান করুন',
  'help_support': 'সাহায্য ও সহযোগিতা',
  'organizations': 'সংস্থাগুলি',
  'hero_act': 'বীরত্বপূর্ণ কাজ!',
  'thank_you': 'ধন্যবাদ!',
  'view_ledger': 'ইমপ্যাক্ট লেজার দেখুন',
  'logout': 'লগ আউট',
  'welcome_back': 'স্বাগতম',
  'social': 'সামাজিক',
  'board': 'বোর্ড',
  'needs': 'প্রয়োজন',
  'total_impact': 'মোট যাচাইকৃত প্রভাব',
  'transparency_journal': 'স্বচ্ছতা জার্নাল',
  'ledger_empty': 'এখনো কোনো যাচাইকৃত বিতরণ রেকর্ড করা হয়নি।',
  'certificate_title': 'টাইনিউইংস হিরো',
  'certificate_subtitle': 'প্রভাবের সার্টিফিকেট',
  'certificate_body': 'এটি আনুষ্ঠানিকভাবে স্বীকৃতি এবং উদযাপনের জন্য জানানো হচ্ছে যে',
  'certificate_footer': 'বাংলাদেশের সুবিধাবঞ্চিত শিশুদের প্রতি তাদের উল্লেখযোগ্য অবদানের জন্য।',
  'faq_title': 'প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী',
  'send_message': 'আমাদের একটি বার্তা পাঠান',
  'category': 'বিভাগ',
  'subject': 'বিষয়',
  'message_label': 'বার্তা',
  'submit_feedback': 'ফিডব্যাক জমা দিন',
  'my_messages': 'আমার বার্তা এবং প্রতিক্রিয়া',
  'top_contributors': 'সেরা অবদানকারী',
  'all_time': 'সর্বকালীন',
  'by_org': 'সংস্থা অনুযায়ী',
  'select_org': 'সংস্থা নির্বাচন করুন',
  'total': 'মোট',
  'sponsors': 'পৃষ্ঠপোষক',
  'donors': 'দাতা',
  'period': 'সময়সীমা',
  'welcome_title': 'টাইনিউইংস',
  'welcome_subtitle': 'প্রয়োজনে শিশুদের সাথে সংযোগ করুন, যত্ন নিন এবং সমর্থন করুন',
  'login': 'লগইন',
  'register': 'নিবন্ধন',
  'start_impact': 'আপনার প্রভাবের যাত্রা শুরু করুন',
  'volunteering': 'স্বেচ্ছাসেবা',
  'search_opps': 'সুযোগ খুঁজুন...',
  'already_applied': 'ইতিমধ্যে আবেদন করা হয়েছে',
  'apply_now': 'আবেদন করুন',
  'add_opportunity': 'সুযোগ পোস্ট করুন',
  'impact_sponsorships': 'প্রভাব পৃষ্ঠপোষকতা',
  'supports_over': 'সহায়তা করে',
  'children': 'শিশুদের',
  'search_orgs': 'সংস্থা খুঁজুন...',
  'dhaka': 'ঢাকা',
  'verified': 'যাচাইকৃত',
  'urgent': 'জরুরী',
  'view_details': 'বিস্তারিত দেখুন',
  'profile_login_prompt': 'আপনার প্রোফাইল দেখতে লগইন করুন',
  'about_me': 'আমার সম্পর্কে',
  'my_impact': 'আমার প্রভাব',
  'quick_actions': 'দ্রুত অ্যাকশন',
  'edit_profile': 'প্রোফাইল এডিট করুন',
  'phone': 'ফোন',
  'profession': 'পেশা',
  'skills': 'দক্ষতা',
  'address': 'ঠিকানা',
  'blood_group': 'রক্তের গ্রুপ',
  'total_contribution': 'মোট অবদান',
  'volunteer_apps': 'স্বেচ্ছাসেবক আবেদন',
  'donation_history': 'দানের ইতিহাস',
  'my_sponsorships': 'আমার পৃষ্ঠপোষকতা',
  'my_applications': 'আমার আবেদন',
  'full_name': 'পুরো নাম',
  'email_address': 'ইমেইল ঠিকানা',
  'bio': 'জীবনী',
  'professional_skills': 'পেশাদার এবং দক্ষতা',
  'v_skills': 'স্বেচ্ছাসেবা দক্ষতা',
  'location_safety': 'অবস্থান এবং নিরাপত্তা',
  'emergency_phone': 'জরুরি ফোন',
  'save_changes': 'পরিবর্তন সংরক্ষণ করুন',
  'successful_update': 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে!',
  'mark_all_read': 'সবগুলো পঠিত হিসেবে চিহ্নিত করুন',
  'no_notifications': 'এখনো কোনো বিজ্ঞপ্তি নেই',
  'opp_board': 'সুযোগ বোর্ড',
  'post_opp': 'সুযোগ পোস্ট করুন',
  'apply_method': 'কিভাবে আবেদন করবেন',
  'deadline': 'সময়সীমা',
  'eligibility': 'যোগ্যতা',
  'contact_method': 'যোগাযোগের পদ্ধতি',
  'jobs': 'চাকরি',
  'scholarships': 'বৃত্তি',
  'admissions': 'ভর্তি',
  'internships': 'ইন্টার্নশিপ',
  'training': 'প্রশিক্ষণ',
  'fellowships': 'ফেলোশিপ',
  'mentorship': 'মেন্টরশিপ',
  'housing': 'আবাসন',
  'opp_posted': 'সুযোগ সফলভাবে পোস্ট করা হয়েছে!',
  'all': 'সব',
  'notifications': 'বিজ্ঞপ্তি',
  'manage': 'ব্যাবস্থাপনা',
};
